USE GOOD_OLD_TIMES_DB;
DELIMITER //
DROP FUNCTION IF EXISTS beautifyDatetimeLarge//
CREATE FUNCTION beautifyDatetimeLarge (d DATETIME)
RETURNS CHAR(70) DETERMINISTIC
BEGIN	
       RETURN DATE_FORMAT( d, '%a %e %M %Y, %H:%i');	
END;

DROP FUNCTION IF EXISTS beautifyDatetimeSmall//
CREATE FUNCTION beautifyDatetimeSmall (d DATETIME)
RETURNS CHAR(40) DETERMINISTIC
BEGIN
       RETURN DATE_FORMAT( d, '%M %e %Y');
END;
