USE GOOD_OLD_TIMES_DB;

DROP VIEW IF EXISTS v_NewsTags_N;
CREATE VIEW v_NewsTags_N 
AS SELECT T.`TAG_NAME`, T.`TAG_STATUS`, VND.`REPORT_NUMBER`, VND.`AUTOR_SIGN`,  
        VND.`EVENT_STREET`, VND.`EVENT_NEIGHBOURHOOD`, VND.`EVENT_CITY`, VND.`EVENT_COUNTRY`, 
        VND.`HEADER`, VND.`REPORT_DESCRIPTION`, VND.`CONTENT`, VND.`LIKES`, VND.`THUMBNAIL`, VND.`EVENT_DATE`, VND.`PUBLICATION_DATE`,
        VND.`CREATION_DATE`, VND.`CREATED_BY_ID`, VND.`CREATED_BY_NAME`,
		VND.`LAST_UPDATE_DATE`, VND.`UPDATED_BY_ID`, VND.`UPDATED_BY_NAME`, VND.`REPORT_STATUS`
FROM news_tags NTG
JOIN tags T
ON NTG.TAG = T.TAG_NAME
JOIN v_News_Detailed VND
ON NTG.REPORT_ID = VND.REPORT_NUMBER

