USE GOOD_OLD_TIMES_DB;

DROP VIEW IF EXISTS v_NewsCategories_N;
CREATE VIEW v_NewsCategories_N 
AS SELECT CTG.`CATEGORY_ID`, CTG.`CATEGORY_NAME`, CTG.`COLOR`, VND.`REPORT_NUMBER`, VND.`AUTOR_SIGN`,  
        VND.`EVENT_STREET`, VND.`EVENT_NEIGHBOURHOOD`, VND.`EVENT_CITY`, VND.`EVENT_COUNTRY`, 
        VND.`HEADER`, VND.`REPORT_DESCRIPTION`, VND.`CONTENT`, VND.`LIKES`, VND.`THUMBNAIL`, VND.`EVENT_DATE`, VND.`PUBLICATION_DATE`,
        VND.`CREATION_DATE`, VND.`CREATED_BY_ID`, VND.`CREATED_BY_NAME`,
		VND.`LAST_UPDATE_DATE`, VND.`UPDATED_BY_ID`, VND.`UPDATED_BY_NAME`, VND.`REPORT_STATUS`
FROM news_categories NCTG
JOIN Categories CTG
ON NCTG.CATEGORY = CTG.CATEGORY_ID
JOIN v_News_Detailed VND
ON NCTG.REPORT_ID = VND.REPORT_NUMBER

