USE GOOD_OLD_TIMES_DB;

DROP VIEW IF EXISTS v_News_Detailed;
CREATE VIEW v_News_Detailed 
AS SELECT NR.`REPORT_ID` AS REPORT_NUMBER, NR.`SIGN` AS AUTOR_SIGN, 
NR.`LOCATION_STREET` AS EVENT_STREET, NR.`LOCATION_NEIGHB` AS EVENT_NEIGHBOURHOOD, NR.`LOCATION_CITY` AS EVENT_CITY, NR.`LOCATION_COUNTRY` AS EVENT_COUNTRY,
NR.`REPORT_HEADER` AS HEADER, NR.`REPORT_DESCRIPTION`, NR.`REPORT_CONTENT` AS CONTENT, NR.`LIKES`, NR.`THUMBNAIL`,
NR.EVENT_DATE, NR.`PUBLICATION_DATE`, NR.`CREATION_DATE`, NR.`CREATED_BY` AS CREATED_BY_ID, UCR.`FULL_NAME` AS CREATED_BY_NAME, 
NR.`LAST_UPDATE_DATE`, NR.`LAST_UPDATED_BY` AS UPDATED_BY_ID, UUP.`FULL_NAME` AS UPDATED_BY_NAME,
`REPORT_STATUS`
FROM NEWS_REPORTS NR
JOIN users UCR
ON UCR.ID_USER = NR.CREATED_BY
JOIN users UUP
ON UUP.ID_USER = NR.LAST_UPDATED_BY;

DROP VIEW IF EXISTS v_News_Search;
CREATE VIEW v_News_Search 
AS SELECT `REPORT_NUMBER`, `AUTOR_SIGN`,  
        `EVENT_STREET`, `EVENT_NEIGHBOURHOOD`, `EVENT_CITY`, `EVENT_COUNTRY`, 
        `HEADER`, `REPORT_DESCRIPTION`, `CONTENT`, `LIKES`, `THUMBNAIL`, `EVENT_DATE`, `PUBLICATION_DATE`,
        ND.`CREATION_DATE`, ND.`CREATED_BY_ID`, ND.`CREATED_BY_NAME`,
		ND.`LAST_UPDATE_DATE`, ND.`UPDATED_BY_ID`, ND.`UPDATED_BY_NAME`, NTG.TAG, NCTG.CATEGORY, CTG.CATEGORY_NAME, `REPORT_STATUS`
        FROM v_news_detailed ND
        JOIN news_categories NCTG
        ON NCTG.REPORT_ID = ND.REPORT_NUMBER
        JOIN categories CTG
        ON NCTG.CATEGORY = CTG.CATEGORY_ID
        JOIN news_tags NTG
        ON NTG.REPORT_ID = ND.REPORT_NUMBER
        JOIN tags T
        ON NTG.TAG = T.TAG_NAME