USE GOOD_OLD_TIMES_DB;

DROP VIEW IF EXISTS v_Sections_Small;
CREATE VIEW v_Sections_Small 
AS SELECT `CATEGORY_ID` AS SECTION_ID, `CATEGORY_NAME` AS SECTION_NAME, `COLOR` AS DISPLAY_COLOR, `ORDER` AS DISPLAY_ORDER, `CREATION_DATE`, `CREATED_BY` AS CREATED_BY_ID, `LAST_UPDATE_DATE`, `LAST_UPDATED_BY` AS UPDATED_BY_ID, `SECTION_STATUS`
FROM categories;

DROP VIEW IF EXISTS v_Sections_Detailed;
CREATE VIEW v_Sections_Detailed 
AS SELECT `CATEGORY_ID` AS SECTION_ID, `CATEGORY_NAME` AS SECTION_NAME, `COLOR` AS DISPLAY_COLOR, `ORDER` AS DISPLAY_ORDER, 
CTG.`CREATION_DATE`, CTG.`CREATED_BY` AS CREATED_BY_ID, UCR.`FULL_NAME` AS CREATED_BY_NAME, 
CTG.`LAST_UPDATE_DATE`, CTG.`LAST_UPDATED_BY` AS UPDATED_BY_ID, UUP.`FULL_NAME` AS UPDATED_BY_NAME,
`SECTION_STATUS`
FROM categories CTG
JOIN users UCR
ON UCR.ID_USER = CTG.CREATED_BY
JOIN users UUP
ON UUP.ID_USER = CTG.LAST_UPDATED_BY